# Generated by Django 5.2 on 2026-05-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fundbalance_payment_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('weekly', 'Mingguan'), ('monthly', 'Bulanan'), ('quarterly', 'Triwulanan'), ('yearly', 'Tahunan')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contributionperiod'),
        ),
    ]
