# Generated by Django 5.2 on 2026-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_contributionperiod_payment_period'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('resident', 'package', 'period'), name='unique_payment_per_period'),
        ),
    ]
