# Generated by Django 5.2 on 2026-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_unique_payment_per_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributiontype',
            name='destination',
            field=models.CharField(choices=[('main_cash', 'Kas RT'), ('social_cash', 'Kas Sosial'), ('owner_cash', 'Uang Meja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fundbalance',
            name='fund_type',
            field=models.CharField(choices=[('main_cash', 'Kas RT'), ('social_cash', 'Kas Sosial'), ('owner_cash', 'Uang Meja')], max_length=20, unique=True),
        ),
    ]
