# Generated by Django 5.2 on 2026-06-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pertemuan RT', max_length=200)),
                ('meeting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('participant_count', models.PositiveIntegerField()),
                ('mc', models.CharField(max_length=50, verbose_name='Pembawa Acara')),
                ('opening_by', models.CharField(max_length=50, verbose_name='Pembukaan Acara oleh')),
                ('tahlil_by', models.CharField(max_length=50, verbose_name='Tahlil dipimpin oleh')),
                ('prayer_by', models.CharField(max_length=50, verbose_name='Doa dipimpin oleh')),
                ('next_meeting', models.CharField(max_length=50)),
                ('preparation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='meetings.meetingnote')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingCashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=0, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=0, max_digits=10)),
                ('final_balance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_reports', to='meetings.meetingnote')),
            ],
        ),
    ]
