# Generated by Django 5.2 on 2026-07-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcashreport',
            name='initial_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
